# Generated by Django 4.1 on 2022-11-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='exe_images/')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
