# Generated by Django 4.1 on 2022-12-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_exe_alter_user_photo_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_images/'),
        ),
    ]
