# Generated by Django 4.1 on 2023-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_photo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='user_photo',
            name='avatar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_images/'),
        ),
    ]
