# Generated by Django 4.1 on 2023-01-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_photo_thumbnail_user_photo_avatar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='avatar_photo',
            field=models.ImageField(blank=True, default='default_photo/avatar.png', null=True, upload_to='avatar_images/'),
        ),
    ]
