# Generated by Django 4.1 on 2023-02-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_photo_avatar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=models.ImageField(blank=True, default='default_photo/avatar.png', null=True, upload_to='user_profile_images/'),
        ),
    ]
