# Generated by Django 4.1 on 2023-03-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_photo_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='anonymous_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='default_photo/avatar.png', null=True, upload_to='')),
            ],
        ),
    ]
