# Generated by Django 4.1 on 2023-04-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_anonymous_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anonymous_user',
        ),
    ]
