# Generated by Django 4.1 on 2023-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_photo_avatar_photo_alter_user_photo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='avatar_photo',
            field=models.ImageField(blank=True, default='avatar_images/avatar.png', null=True, upload_to='avatar_images/'),
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=models.ImageField(blank=True, default='user_profile_images/avatar.png', null=True, upload_to='user_profile_images/'),
        ),
    ]
