# Generated by Django 4.1 on 2023-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_photo_avatar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='avatar_photo',
            field=models.ImageField(default='avatar_images/avatar.png', upload_to='avatar_images/'),
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=models.ImageField(default='user_profile_images/brave.jpeg', upload_to='user_profile_images/'),
        ),
    ]
