# Generated by Django 4.0.4 on 2025-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_photo_avatar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=models.ImageField(blank=True, default='user_profile_images/10.jpg', null=True, upload_to='user_profile_images/'),
        ),
    ]
