# Generated by Django 4.0.4 on 2025-12-08 11:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_photo_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_photo',
            name='avatar_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='user_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_profile'),
        ),
    ]
