# Generated by Django 4.1 on 2023-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comments2_article_comment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment2',
        ),
        migrations.AddField(
            model_name='article',
            name='comment2',
            field=models.ManyToManyField(blank=True, null=True, to='articles.comments2'),
        ),
    ]
