# Generated by Django 4.1 on 2023-01-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_comment2_article_comment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment2',
        ),
        migrations.AddField(
            model_name='article',
            name='comment2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comments2'),
        ),
    ]
