# Generated by Django 4.1 on 2023-02-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0014_alter_comments_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_star_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('star_1', models.ManyToManyField(blank=True, related_name='star_1', to=settings.AUTH_USER_MODEL)),
                ('star_2', models.ManyToManyField(blank=True, related_name='star_2', to=settings.AUTH_USER_MODEL)),
                ('star_3', models.ManyToManyField(blank=True, related_name='star_3', to=settings.AUTH_USER_MODEL)),
                ('star_4', models.ManyToManyField(blank=True, related_name='star_4', to=settings.AUTH_USER_MODEL)),
                ('star_5', models.ManyToManyField(blank=True, related_name='star_5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
