# Generated by Django 4.1 on 2023-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_users_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
