# Generated by Django 4.1 on 2023-04-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_join_basket_basket_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_book',
            name='xxx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.join_basket'),
        ),
    ]
