# Generated by Django 4.1 on 2023-04-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_basket_book_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_book',
            name='xxx',
        ),
        migrations.AddField(
            model_name='join_basket',
            name='xxx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.basket_book'),
        ),
    ]
