# Generated by Django 4.1 on 2023-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_alter_join_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_basket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='join_basket',
            name='xxx',
        ),
        migrations.DeleteModel(
            name='basket_book',
        ),
        migrations.DeleteModel(
            name='join_basket',
        ),
    ]
