# Generated by Django 4.1 on 2024-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_remove_join_basket_user_remove_join_basket_xxx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
