# Generated by Django 4.0.4 on 2025-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_article_writer_alter_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
